# Server
server.port=8080

# Logging
logging.level.com.arabicleveldetector=DEBUG
logging.file.name=logs/application.log

# File Paths
training.data.file=data/arabic_text_level.xlsx
model.save.path=model/model.zip
# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html